name: CI (.NET)

on:
  push:
    branches: [ "main" ]
  pull_request: 
    branches: ["main"]
jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore
        run: dotnet restore ./API_AUTENTICATION.csproj

      - name: Build
        run: dotnet build ./API_AUTENTICATION.csproj -c Release --no-restore

 
